PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX si: <https://si-digital-framework.org/SI#> 
SELECT  ?EnLabel ?FrLabel   (?PrefixSymbol AS ?Symbol) ?Factor ?dataType 
WHERE { {  
	 		?SIPrefix si:hasSymbol ?PrefixSymbol ; skos:prefLabel ?EnLabel;  skos:prefLabel ?FrLabel; si:hasScalingFactor ?Factor ;  si:hasDatatype ?dataType . 
} 
FILTER  (lang(?EnLabel)='en').  FILTER  (lang(?FrLabel )='en').  }  order by ?Factor
